// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClHjhQ8UYT5MoMgsa3BIhLUs44uae02U0',
    appId: '1:369577605654:web:33b6da889efe0179115337',
    messagingSenderId: '369577605654',
    projectId: 'flutter-rpg-49be7',
    authDomain: 'flutter-rpg-49be7.firebaseapp.com',
    storageBucket: 'flutter-rpg-49be7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQxZay5CkgsDhfkHPSllOI4mNfcRhJbNo',
    appId: '1:369577605654:android:f8751ad78302667a115337',
    messagingSenderId: '369577605654',
    projectId: 'flutter-rpg-49be7',
    storageBucket: 'flutter-rpg-49be7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOm-kUB8owXLL3mhB4tTlf3MZsZI7oY1Y',
    appId: '1:369577605654:ios:5b04e02dbee32e41115337',
    messagingSenderId: '369577605654',
    projectId: 'flutter-rpg-49be7',
    storageBucket: 'flutter-rpg-49be7.firebasestorage.app',
    iosBundleId: 'com.example.rpg',
  );

}